# Generated by Django 3.2.15 on 2022-11-16 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0006_auto_20221116_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerproject',
            old_name='city_project',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='offerproject',
            old_name='district_project',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='offerproject',
            old_name='division_project',
            new_name='division',
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 11, 16, 17, 10, 56, 98270, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 16, 17, 10, 56, 95274, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 16, 17, 10, 56, 96275, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 16, 17, 10, 56, 96275, tzinfo=utc), max_length=20),
        ),
    ]
