# Generated by Django 3.2.15 on 2022-11-18 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0017_auto_20221119_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerprojectroomtype',
            name='type_room',
        ),
        migrations.AddField(
            model_name='offerprojectroomtype',
            name='choices_rooms',
            field=models.IntegerField(blank=True, choices=[(0, '1+1'), (1, '2+1'), (2, '3+1'), (3, '4+1'), (4, '5+1'), (4, '6+1'), (4, '7+1'), (3, '4+2'), (4, '5+2'), (4, '6+2'), (4, '7+2')], null=True),
        ),
        migrations.AddField(
            model_name='offerprojectroomtype',
            name='type_offer',
            field=models.IntegerField(blank=True, choices=[(0, 'Flat'), (1, 'Villa'), (2, 'Commercial')], null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 11, 18, 22, 54, 52, 394022, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 18, 22, 54, 52, 390680, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 18, 22, 54, 52, 391683, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 18, 22, 54, 52, 391683, tzinfo=utc), max_length=20),
        ),
    ]
