# Generated by Django 3.2.15 on 2022-11-19 04:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0019_auto_20221119_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 4, 31, 32, 669092, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 4, 31, 32, 666095, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 4, 31, 32, 667094, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 4, 31, 32, 667094, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='offerprojectvideoss',
            name='links',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
