# Generated by Django 3.2.15 on 2022-11-19 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0021_auto_20221119_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproject',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 16, 57, 51, 549146, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 16, 57, 51, 549146, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 16, 57, 51, 549146, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 16, 57, 51, 549146, tzinfo=utc), max_length=20),
        ),
    ]
