# Generated by Django 3.2.15 on 2022-11-19 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0022_auto_20221119_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 17, 9, 5, 87338, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 17, 9, 5, 79339, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 17, 9, 5, 81346, tzinfo=utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 17, 9, 5, 80339, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='offerproject',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
