# Generated by Django 4.1.7 on 2023-02-16 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0026_offerproject_starting_price_alter_address_addressof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 18, 25, 7, 279330, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 18, 25, 7, 279330, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 18, 25, 7, 279330, tzinfo=datetime.timezone.utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 18, 25, 7, 279330, tzinfo=datetime.timezone.utc), max_length=20),
        ),
    ]
