# Generated by Django 4.1.7 on 2023-02-17 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0027_alter_address_addressof_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproject',
            name='citizenship',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Unknown')], default='3'),
        ),
        migrations.AddField(
            model_name='offerproject',
            name='residence_permit',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Unknown')], default='3'),
        ),
        migrations.AddField(
            model_name='offerproject',
            name='view',
            field=models.IntegerField(choices=[(1, 'Sea'), (2, 'Garden'), (3, 'Mountain'), (4, 'Lake'), (5, 'Mountain'), (6, 'River'), (7, 'None')], default='7'),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2023, 2, 17, 18, 33, 55, 433303, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 17, 18, 33, 55, 416393, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 17, 18, 33, 55, 416393, tzinfo=datetime.timezone.utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 17, 18, 33, 55, 416393, tzinfo=datetime.timezone.utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='offercompany',
            name='status_of_partner',
            field=models.IntegerField(choices=[(1, 'Partner'), (2, 'Not a partner')], default=0),
        ),
        migrations.AlterField(
            model_name='offerproject',
            name='type_of_project',
            field=models.IntegerField(blank=True, choices=[(1, 'Villa'), (2, 'Apartment'), (2, 'Commercial')], null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status_of_partner',
            field=models.IntegerField(choices=[(1, 'Partner'), (2, 'Not a partner')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_project',
            field=models.IntegerField(choices=[(1, 'Villa'), (2, 'Apartment'), (2, 'Commercial')], default=0),
        ),
    ]
