# Generated by Django 4.1.7 on 2023-02-18 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0028_offerproject_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 16, 54, 31, 456028, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 16, 54, 31, 440406, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 16, 54, 31, 456028, tzinfo=datetime.timezone.utc), max_length=40),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 16, 54, 31, 440406, tzinfo=datetime.timezone.utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='offerproject',
            name='citizenship',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, '-')], default='3'),
        ),
        migrations.AlterField(
            model_name='offerproject',
            name='residence_permit',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, '-')], default='3'),
        ),
        migrations.AlterField(
            model_name='offerproject',
            name='view',
            field=models.IntegerField(choices=[(1, 'Sea'), (2, 'Garden'), (3, 'Mountain'), (4, 'Lake'), (5, 'Mountain'), (6, 'River'), (7, '-')], default='7'),
        ),
    ]
